---
- name: Configure the Jenkins APT key
  apt_key: url=http://pkg.jenkins.io/debian/jenkins.io.key
           state=present

- name: Configure the Jenkins APT repositories
  apt_repository:
    repo: deb http://pkg.jenkins-ci.org/debian binary/
    state: present
    update_cache: yes

- name: Install Jenkins
  apt: pkg=jenkins={{ jenkins_version }} state=present

- name: Set user-defined configuration options
  template:
    src: templates/jenkins.j2
    dest: /etc/default/jenkins

- name: Enable the Jenkins service
  service: name=jenkins enabled=yes state=restarted
